### ISSUE TITLE
初始化配置失败

### ISSUE THREAD

**Issue by UnicornLinYI** [79percent/taro-useModel#1]
+ 插件配置的时候名称有问题
+ 运行时报错（ handleErrorFromBinding(ctx);）
<img width="848" alt="image" src="https://github.com/79percent/taro-useModel/assets/52225311/49614481-0f00-46a0-b644-20a92c70bd85">

**Comment by 79percent** [comment]
感谢提出问题，应该是发布时少了一些文件，可将插件版本升级至1.0.2 可以解决
